# Generated by Django 4.2.7 on 2023-11-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('city', models.CharField(choices=[('COS', 'Colorado Springs'), ('DEN', 'Denver'), ('FTC', 'Fort Collins')], max_length=200, verbose_name='Location')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Phone')),
                ('is_open', models.BooleanField(blank=True, default=True, verbose_name='Open')),
                ('about', models.TextField(blank=True)),
            ],
        ),
    ]
