# Generated by Django 4.2.7 on 2023-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0004_alter_business_city_delete_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='NHLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[{'Montréal Canadiens', 'MTL'}, {'TOR', 'Toronto Maple Leafs'}, {'Boston Bruins', 'BOS'}, {'NYR', 'New York Rangers'}, {'Chicago Blackhawks', 'CHI'}, {'DET', 'Detroit Red Wings'}, {'Los Angeles Kings', 'LAK'}, {'Dallas Stars', 'DAL'}, {'PHI', 'Philadelphia Flyers'}, {'PIT', 'Pittsburgh Penguins'}, {'St. Louis Blues', 'STL'}, {'Buffalo Sabres', 'BUF'}, {'Vancouver Canucks', 'VAN'}, {'Calgary Flames', 'CGY'}, {'NYI', 'New York Islanders'}, {'NJD', 'New Jersey Devils'}, {'Washington Capitals', 'WSH'}, {'Edmonton Oilers', 'EDM'}, {'CAR', 'Carolina Hurricanes'}, {'Colorado Avalanche', 'COL'}, {'Arizona Coyotes', 'ARI'}, {'San Jose Sharks', 'SJS'}, {'Ottawa Senators', 'OTT'}, {'Tampa Bay Lightning', 'TBL'}, {'ANA', 'Anaheim Ducks'}, {'FLA', 'Florida Panthers'}, {'Nashville Predators', 'NSH'}, {'WPG', 'Winnipeg Jets'}, {'CBJ', 'Columbus Blue Jackets'}, {'MIN', 'Minnesota Wild'}, {'VGK', 'Vegas Golden Knights'}, {'SEA', 'Seattle Kraken'}], max_length=50, verbose_name='Name')),
            ],
        ),
    ]
