# Generated by Django 4.2.7 on 2023-11-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0005_nhlteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='uid',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nhlteam',
            name='name',
            field=models.CharField(choices=[('Montréal Canadiens', 'Montréal Canadiens'), ('Toronto Maple Leafs', 'Toronto Maple Leafs'), ('Boston Bruins', 'Boston Bruins'), ('New York Rangers', 'New York Rangers'), ('Chicago Blackhawks', 'Chicago Blackhawks'), ('Detroit Red Wings', 'Detroit Red Wings'), ('Los Angeles Kings', 'Los Angeles Kings'), ('Dallas Stars', 'Dallas Stars'), ('Philadelphia Flyers', 'Philadelphia Flyers'), ('Pittsburgh Penguins', 'Pittsburgh Penguins'), ('St. Louis Blues', 'St. Louis Blues'), ('Buffalo Sabres', 'Buffalo Sabres'), ('Vancouver Canucks', 'Vancouver Canucks'), ('Calgary Flames', 'Calgary Flames'), ('New York Islanders', 'New York Islanders'), ('New Jersey Devils', 'New Jersey Devils'), ('Washington Capitals', 'Washington Capitals'), ('Edmonton Oilers', 'Edmonton Oilers'), ('Carolina Hurricanes', 'Carolina Hurricanes'), ('Colorado Avalanche', 'Colorado Avalanche'), ('Arizona Coyotes', 'Arizona Coyotes'), ('San Jose Sharks', 'San Jose Sharks'), ('Ottawa Senators', 'Ottawa Senators'), ('Tampa Bay Lightning', 'Tampa Bay Lightning'), ('Anaheim Ducks', 'Anaheim Ducks'), ('Florida Panthers', 'Florida Panthers'), ('Nashville Predators', 'Nashville Predators'), ('Winnipeg Jets', 'Winnipeg Jets'), ('Columbus Blue Jackets', 'Columbus Blue Jackets'), ('Minnesota Wild', 'Minnesota Wild'), ('Vegas Golden Knights', 'Vegas Golden Knights'), ('Seattle Kraken', 'Seattle Kraken')], max_length=50, verbose_name='Name'),
        ),
    ]
