# Generated by Django 4.2.7 on 2023-11-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0006_business_uid_alter_nhlteam_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='uid',
            new_name='Username',
        ),
    ]
