# Generated by Django 4.2.7 on 2023-11-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0007_rename_uid_business_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='Username',
        ),
    ]
