# Generated by Django 4.2.7 on 2023-11-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0008_remove_business_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='Username',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
