# Generated by Django 4.2.7 on 2023-11-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0009_business_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='business',
            name='password',
            field=models.CharField(default=None, max_length=200, verbose_name='Password'),
        ),
    ]
