# Generated by Django 4.2.7 on 2023-11-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0010_business_last_login_business_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='Username',
        ),
    ]
