# Generated by Django 4.2.7 on 2023-11-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0011_remove_business_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='username',
            field=models.CharField(default=models.CharField(max_length=200, verbose_name='Name'), max_length=50, verbose_name='Username'),
        ),
    ]
