# Generated by Django 4.2.7 on 2023-11-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0012_business_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(default=None, max_length=200, verbose_name='Password')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='business',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='business',
            name='password',
        ),
        migrations.RemoveField(
            model_name='business',
            name='username',
        ),
    ]
