# Generated by Django 4.2.7 on 2023-11-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0014_user_fav_biz_user_fav_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='home',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='gp_app.nhlteam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_biz',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='gp_app.business', verbose_name='Favorite Business'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_team',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='gp_app.nhlteam', verbose_name='Favorite Team'),
        ),
    ]
