# Generated by Django 4.2.7 on 2023-11-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0016_remove_business_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fav_biz',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fav_team',
            new_name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('Colorado Springs', 'Colorado Springs'), ('Denver', 'Denver'), ('Fort Collins', 'Fort Collins')], default=None, max_length=200, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_biz',
            field=models.BooleanField(blank=True, default=False, verbose_name='Business'),
        ),
    ]
